export const metadata = {
  title: "FAQ – FreeQR | Free QR Code Generator Support",
  description:
    "Common questions about generating UPI, WiFi, vCard, WhatsApp, and Email QR codes with FreeQR's privacy-first tool.",
};

export default function FAQPage() {
  const faqs = [
    {
      q: "How do I create a UPI QR code for payments?",
      a: "To generate a UPI QR code, select the 'UPI' option, enter your Virtual Payment Address (VPA) like 'yourname@bank', and specify the amount if needed. This code allows users to scan and pay you instantly using apps like Google Pay, PhonePe, or Paytm.",
    },
    {
      q: "Is it safe to generate a WiFi QR code here?",
      a: "Yes. Our WiFi QR generator works client-side. When you enter your network SSID and password, the data is processed in your browser. This creates a secure way for guests to join your network without you having to reveal your password in plain text.",
    },
    {
      q: "What information can I include in a vCard QR code?",
      a: "A vCard (Virtual Business Card) QR code can store your full name, phone number, email address, website, and company details. When scanned, it prompts the smartphone to automatically save your details to the user's contact list.",
    },
    {
      q: "How do WhatsApp and Email QR codes work?",
      a: "These codes use 'mailto:' and 'wa.me' protocols. You can pre-fill a recipient's email address or phone number along with a custom message. When scanned, the user's messaging or email app opens with the fields already filled out.",
    },
    {
      q: "Are the QR codes generated by FreeQR permanent?",
      a: "Yes. FreeQR creates 'Static QR Codes.' The information is embedded directly into the pattern. As long as your link is active or your WiFi credentials don't change, the QR code will work forever with no expiration date.",
    },
    {
      q: "Why should I use a Text QR code?",
      a: "Text QR codes are perfect for sharing information offline. You can encode instructions, serial numbers, or notes. They do not require an internet connection to be decoded by a scanner.",
    },
    {
      q: "Can I use these QR codes for my business?",
      a: "Absolutely. All QR codes generated here are high-resolution and free for commercial use. You can print them on business cards, menus, packaging, or marketing banners without any hidden fees or watermarks.",
    },
    {
      q: "Do you track the scans or store my data?",
      a: "No. Unlike other services, we do not track how many times your code is scanned, nor do we store the content you encode. Your privacy is our core mission; all generation happens locally on your device.",
    }
  ];

  return (
    <section className="bg-background py-24 border-t border-borderDark">
      <div className="max-w-4xl mx-auto px-6 space-y-16">

        {/* Header */}
        <div className="text-center max-w-2xl mx-auto">
          <h1 className="text-4xl font-bold text-textPrimary">
            Detailed FAQ & Usage Guide
          </h1>
          <p className="mt-4 text-textSecondary text-lg">
            Learn more about our various QR types including UPI, WiFi, vCard, and more.
          </p>
        </div>

        {/* FAQ List */}
        <div className="space-y-6">
          {faqs.map((item, i) => (
            <div
              key={i}
              className="bg-surface border border-borderDark rounded-xl p-6 hover:shadow-md transition-shadow duration-200"
            >
              <h2 className="text-lg font-semibold text-textPrimary flex items-start gap-3">
                <span className="text-primary font-bold">Q:</span>
                {item.q}
              </h2>
              <div className="mt-3 text-textSecondary leading-relaxed pl-7">
                {item.a}
              </div>
            </div>
          ))}
        </div>

        {/* AdSense Value Addition: Technical Specs Section */}
        <div className="grid sm:grid-cols-2 gap-8 pt-10 border-t border-borderDark">
          <div className="space-y-3">
            <h3 className="font-bold text-textPrimary text-xl">Technical Accuracy</h3>
            <p className="text-sm text-textSecondary">
              Our generator adheres to the <strong>ISO/IEC 18004</strong> standard. This ensures that every QR code created—whether for a simple URL or complex vCard—is compatible with all modern iOS, Android, and dedicated hardware scanners.
            </p>
          </div>
          <div className="space-y-3">
            <h3 className="font-bold text-textPrimary text-xl">High Error Correction</h3>
            <p className="text-sm text-textSecondary">
              We use <strong>Level H (High)</strong> error correction for our QR codes. This means your code can remain scannable even if up to 30% of the surface is damaged or obscured, making them ideal for physical printing.
            </p>
          </div>
        </div>

        {/* Footer CTA */}
        <div className="text-center pt-10">
          <p className="text-sm text-textSecondary">
            Need a custom solution or found a bug? 
            <a
              href="/contact"
              className="ml-1 text-primary font-medium hover:underline"
            >
              Contact Support →
            </a>
          </p>
        </div>

      </div>
    </section>
  );
}